ansible_user: "{{ lookup('env','SA_WINDOWS_USER_LAB') }}"
ansible_password: "{{ lookup('env','SA_WINDOWS_PASSWORD_LAB') }}"

# Linux SSH placeholders (env-scoped)
linux_ansible_user: "{{ lookup('env','SA_LINUX_USER_LAB') }}"
linux_ssh_private_key_file: "{{ lookup('env','SA_LINUX_SSH_KEY_PATH_LAB') }}"
linux_become: true
linux_become_user: root