all:
  children:
    windows_ui_path_orchestrator:
      hosts:
        dev-uip-orch-01:
        dev-uip-orch-02:
    windows_ui_path_test_manager:
      hosts:
        dev-uip-tm-01:
        dev-uip-tm-02:
    windows_web_api:
      hosts:
        dev-web-api-01:
        dev-web-api-02:
    windows_web_elasticsearch:
      hosts:
        dev-web-es-01:
        dev-web-es-02:
    windows_build_server_gitlab_runner:
      hosts:
        dev-build-glr-01:
        dev-build-glr-02:
    windows_sql_server:
      hosts:
        dev-sql-01:
        dev-sql-02:
