all:
  children:
    windows_ui_path_orchestrator:
      hosts:
        lab-uip-orch-01:
        lab-uip-orch-02:
    windows_ui_path_test_manager:
      hosts:
        lab-uip-tm-01:
        lab-uip-tm-02:
    windows_web_api:
      hosts:
        lab-web-api-01:
        lab-web-api-02:
    windows_web_elasticsearch:
      hosts:
        lab-web-es-01:
        lab-web-es-02:
    windows_build_server_gitlab_runner:
      hosts:
        lab-build-glr-01:
        lab-build-glr-02:
    windows_sql_server:
      hosts:
        lab-sql-01:
        lab-sql-02:
    linux_tools_vm:
      hosts:
        lab-linux-tools-01:
        lab-linux-tools-02:
    linux_app_vm:
      hosts:
        lab-linux-app-01:
        lab-linux-app-02: