- name: Configure Windows Web Elasticsearch servers
  hosts: windows_web_elasticsearch
  gather_facts: false
  vars_files:
    - ../../group_vars_common/windows/connection.yml
    - ../../group_vars_common/windows/windows_web_elasticsearch.yml
  roles: "{{ windows_web_elasticsearch_roles }}"
