all:
  children:
    windows_ui_path_orchestrator:
      hosts:
        prd-uip-orch-01:
        prd-uip-orch-02:
    windows_ui_path_test_manager:
      hosts:
        prd-uip-tm-01:
        prd-uip-tm-02:
    windows_web_api:
      hosts:
        prd-web-api-01:
        prd-web-api-02:
    windows_web_elasticsearch:
      hosts:
        prd-web-es-01:
        prd-web-es-02:
    windows_build_server_gitlab_runner:
      hosts:
        prd-build-glr-01:
        prd-build-glr-02:
    windows_sql_server:
      hosts:
        prd-sql-01:
        prd-sql-02:
    windows_development_toolbox_base_profile:
      children:
        windows_toolbox_team_alpha:
        windows_toolbox_team_beta:
        windows_toolbox_team_gamma:
        windows_toolbox_team_delta:
    windows_toolbox_team_alpha:
      hosts:
        prd-toolbox-alpha-01:
        prd-toolbox-alpha-02:
    windows_toolbox_team_beta:
      hosts:
        prd-toolbox-beta-01:
        prd-toolbox-beta-02:
    windows_toolbox_team_gamma:
      hosts:
        prd-toolbox-gamma-01:
        prd-toolbox-gamma-02:
    windows_toolbox_team_delta:
      hosts:
        prd-toolbox-delta-01:
        prd-toolbox-delta-02:
    linux_tools_vm:
      hosts:
        prd-linux-tools-01:
        prd-linux-tools-02:
    linux_app_vm:
      hosts:
        prd-linux-app-01:
        prd-linux-app-02: